spring:
  config:
    import: optional:file:.env[.properties],optional:file:backend/.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5433/fitgym
    username: fitgym_user
    password: fitgym_pass

  jpa:
    hibernate:
      ddl-auto: validate

tpvv:
  base-url: ${TPVV_BASE_URL:https://tpv-backend-cbbg.onrender.com}
  api-key: ${TPVV_API_KEY:}
  callback-url-registro: ${TPVV_CALLBACK_URL_REGISTRO:http://localhost:5173/registro}
  callback-url-monedero: ${TPVV_CALLBACK_URL_MONEDERO:http://localhost:5173/perfil}

# logging:
#   level:
#     org.springframework.boot.context.config: TRACE
#     org.springframework.jdbc.datasource: DEBUG
