spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/fitgym
    username: fitgym_user
    password: fitgym_pass

  jpa:
    hibernate:
      ddl-auto: validate

# logging:
#   level:
#     org.springframework.boot.context.config: TRACE
#     org.springframework.jdbc.datasource: DEBUG
